spring:
  config:
    activate:
      on-profile: local-db

  datasource:
    url: ${LOCAL_DB_URL}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${LOCAL_DB_HOST}
    password: ${LOCAL_DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: none

    properties:
      hibernate:
        format_sql: true

    database: mysql

    database-platform: org.hibernate.dialect.MySQL8Dialect

  #    show-sql: true

  jackson:
    property-naming-strategy: SNAKE_CASE

  flyway:
    enabled: true
    baseline-on-migrate: true
    out-of-order: true

logging.level:
  org.hibernate.SQL: debug
  #  org.hibernate.type: trace
  org.springframework.security: debug

dbInfo: rds

---

spring:
  config:
    activate:
      on-profile: prod-db

  datasource:
    url: ${LOCAL_DB_URL}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${LOCAL_DB_HOST}
    password: ${LOCAL_DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: none

    properties:
      hibernate:
        format_sql: true

    database: mysql

    database-platform: org.hibernate.dialect.MySQL8Dialect

  #    show-sql: true

  jackson:
    property-naming-strategy: SNAKE_CASE

  flyway:
    enabled: true
    baseline-on-migrate: true
    out-of-order: true

  dbInfo: rds

logging.level:
  org.hibernate.SQL: debug
  #  org.hibernate.type: trace
  org.springframework.security: debug

